### ISSUE TITLE
Parse error: chunk truncated

### ISSUE THREAD

**Issue by Jesse2431** [hcs64/ww2ogg#21]
I tried converting a .wav with RIFX header to ogg, but I'm getting a error saying: "Parse error: chunk truncated"

Is this a technical error or is it just something weird I got to fix myself?

What I did is trying to convert a .wav RIFX file extracted from a .pck with Ravioli to a OGG Vorbis

**Comment by hcs64** [comment]
This is almost certainly due to a bad or partial extraction, that error indicates that the file is too small for the data described in the header.

Sometimes this happens because a bank file contains only the beginning of a sound, to be resident in memory, while the rest of the data (or all the data with the header repeated) is in a separate file, to be streamed. Do the extracted .wav files seem far too small for what you expect them to contain? You might want to look for .wem files elsewhere in the game filesystem.

Sometimes it's just a bug in the extractor, a common mistake is that the whole file will be 4 or 8 bytes short. I don't know if that's the case with Ravioli, maybe check for a newer version.

This comes up a lot (see #16, #18), I should add it to the readme.

**Comment by Jesse2431** [comment]
I suppose it is a Ravioli bug then yes

The file is indeed a bit small for what I except from it. Neither one of the files is a MB or bigger

I will try something different to extract it, I'm not really sure what though. Would appreciate help with that.
