### ISSUE TITLE
Corrupt decode for Middle Earth: Shadows of Mordor

### ISSUE THREAD

**Issue by hcs64** [hcs64/ww2ogg#3]
From Alpha23: "Hello! Here are some wwise files that are converted errornously by ww2ogg: https://ipfs.io/ipfs/QmQtUCBoPv8QMqsV8RZkxkfr6yvihyxxgU9r2ptnu1kb3S/_corrupt_wwise.7z
They are from the PS3 version of Middle Earth: Shadows of Mordor. Can we get an update? :)"

My response: "It's not obvious what needs to be done, and I'm not up to grab the latest wwise sdk and disassemble it to see what's going wrong now. The fact that there are no streaming errors suggests that there is something very subtle that has changed."

**Comment by MMOSimca** [comment]
I had this issue (no errors but result doesn't play) with a very recent game. I used this program I found on google called 'revorb' on the result from ww2ogg, and it works perfectly now.

https://www.hydrogenaud.io/forums/lofiversion/index.php/t64328.html

Maybe same problem with those files? I can't tell because the download links are all dead for that multiup.org archive.

**Comment by hcs64** [comment]
Yeah, I know about revorb, it's very handy to fix up the output from ww2ogg (it makes smaller files as ww2ogg puts each packet on a separate page, and it fixes the granulepos so that it plays properly in foobar2000 and such).

It doesn't seem to help with this issue, though.

I've put an IPFS mirror for the _corrupt_wwise.7z file in the first post, the original link was http://www.multiup.org/download/ccbf97c35b13e16396e3778eec443a6a/_corrupt_wwise.7z

And just in case here's a mirror for revorb.exe:
https://ipfs.io/ipfs/QmVgjfU7qgPEtANatrfh7VQJby9t1ojrTbN7X8Ei4djF4e/revorb.exe

**Comment by hcs64** [comment]
This is "fixed" in ww2ogg 0.24, you need to use the --no-mod-packets command line option.
